version: '2.4'

services:

    apibcb:
        container_name: apibcb
        environment:
            - VIRTUAL_HOST=api.apibcb.local
            - PHP_VERSION_SHORT=8.2
            - PHPINI_OPEN_BASEDIR=/app
            - PHPFPM_LOG_LEVEL=debug
            - VIRTUAL_PORT=80
            - ALLOW_URL_FOPEN=On
            - LOG_FILE=api.log
            - PUBLIC_ROOT=public
            - NGINX_POLICY=Content-Security-Policy-Report-Only
            - NGINX_POLICY_VALUE=default-src self;
            - STATIC_URL=/static
            - STATIC_PATH=/app/static
        image: ghcr.io/parisprobr/server-tools:php-8.2
        hostname: api.apibcb.local
        depends_on:
            - apibcb-db
            - pedraMoura-nginx-proxy
            - composer-apibcb
        command: bash -c 'chmod +x /root/scripts/start.sh; /root/scripts/start.sh'
        restart: always
        volumes:
            - ./:/app
            - ./storage/logs:/var/log/export
            - ./docker/scripts/start.sh:/root/scripts/start.sh
        env_file:
            - ../apibcb/.env

    composer-apibcb:
        image: composer:2.5
        network_mode: host
        container_name: composer-apibcb
        user: "${UID}:${UID}"
        command: composer install
        volumes:
            - ./:/app
            - ${HOME}:${HOME}
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro

    apibcb-db:
        container_name: apibcb-db
        environment:
            MYSQL_ROOT_PASSWORD: kK123KFTah78dAiv
            MYSQL_DATABASE: apibcb
            MYSQL_USER: apibcb
            MYSQL_PASSWORD: kK123KFTah78dAiv
        image: mysql:5.7
        volumes:
            - ./database/mysql:/var/lib/mysql
        env_file: ./.env

    phpmyadmin-apibcb:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-apibcb
        restart: on-failure
        links:
            - apibcb-db
        environment:
            PMA_HOSTS: apibcb-db
            VIRTUAL_HOST: mysql.apibcb.local
        depends_on:
            - apibcb-db
    
    apibcb-redis:
        image: redis:latest
        container_name: apibcb-redis
        ports:
            - "6379:6379"